### ISSUE TITLE
the RGB+xy+mask is [batchsize,h,w,6],  pretrained FCN model doesn't work.

### ISSUE THREAD

**Issue by MLjian** [MatthewKleinsmith/portraitseg#1]
Hi,guy!
The pretrained FCN model's input image is [batchsize,h,w,3], but the RGB+xy+mask is [batchsize,h,w,6]. So, I think the pretrained FCN model doesn't work when the input is [batchsize,h,w,6]. What do you think of it?

**Comment by MattKleinsmith** [comment]
You're correct in that the pretrained FCN won't work for the six-channel inputs. This is why you'll need to use PortraitFCN+:

https://github.com/MatthewKleinsmith/portraitseg/blob/master/portraitseg/portraitfcn.py#L185

PortraitFCN+ adds three new channels to the pretrained FCN, along with some new untrained weights that correspond to the new channels.

---

Note: This repo is in a very experimental stage. I have not finished it, nor have I polished it for use. Use parts from it at your own risk. Feel free to keep asking questions, though.
